/* CASA BANKO Rewards tab */
(function(){
 const $=id=>document.getElementById(id), trades=()=>{try{return JSON.parse(localStorage.getItem('casaBankoTrades')||'[]')}catch(e){return[]}};
 const arr=v=>Array.isArray(v)?v:(v?[v]:[]);
 function parts(t){let trade=+t.pnl||0,bonus=0;if(t.plan==='YES')bonus+=20;if(t.grade==='A')bonus+=15;if(t.grade==='A+')bonus+=25;if(t.screenshotName)bonus+=10;if((t.notes||'').trim())bonus+=10;if(arr(t.bosTF).some(x=>x!=='NONE'))bonus+=10;if(arr(t.entryTF).some(x=>x!=='NONE'))bonus+=10;let perfect=t.plan==='YES'&&['A','A+'].includes(t.grade)&&!!t.screenshotName&&!!(t.notes||'').trim();if(perfect)bonus+=25;return{trade,bonus,total:trade+bonus,perfect}}
 function kd(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
 function streak(a){let dates=[...new Set(a.filter(t=>t.plan==='YES').map(t=>new Date(t.date||t.savedAt)).filter(d=>!isNaN(d)).map(kd))].sort().reverse(),n=0,c=new Date();c.setHours(0,0,0,0);for(let i=0;i<370&&dates.length;i++){let k=kd(c);if(dates.includes(k)){n++;c.setDate(c.getDate()-1)}else if(i===0)c.setDate(c.getDate()-1);else break}return n}
 function maxWinStreak(a){let n=0,b=0;[...a].sort((x,y)=>new Date(x.date||x.savedAt)-new Date(y.date||y.savedAt)).forEach(t=>{if(t.result==='WIN'){n++;b=Math.max(b,n)}else if(t.result==='LOSS')n=0});return b}
 function levelInfo(balance){const levels=[['ROOKIE BANKO',0],['DISCIPLINED BANKO',250],['CERTIFIED BANKO',500],['BANKO BOSS',1000],['CASA ELITE',2500],['BANKO LEGEND',5000]];let i=0;for(let j=0;j<levels.length;j++)if(balance>=levels[j][1])i=j;let next=levels[Math.min(i+1,levels.length-1)],floor=levels[i][1],cap=next[1],pct=i===levels.length-1?100:Math.max(0,Math.min(100,(balance-floor)/(cap-floor)*100));return{levels,i,name:levels[i][0],next,pct}}
 function renderRewards(){let a=trades(),ps=a.map(parts),balance=Math.round(ps.reduce((s,p)=>s+p.total,0)),bonus=Math.round(ps.reduce((s,p)=>s+p.bonus,0)),li=levelInfo(balance),plan=a.filter(t=>t.plan==='YES').length,ap=a.filter(t=>['A','A+'].includes(t.grade)).length,shots=a.filter(t=>t.screenshotName).length,perfect=ps.filter(p=>p.perfect).length,st=streak(a),ws=maxWinStreak(a),now=new Date(),weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));weekStart.setHours(0,0,0,0);let weekPlan=a.filter(t=>{let d=new Date(t.date||t.savedAt);return !isNaN(d)&&d>=weekStart&&t.plan==='YES'}).length;
 const missions=[['FOLLOW THE PLAN',Math.min(plan,25),25,'25 plan-followed trades'],['A / A+ EXECUTION',Math.min(ap,10),10,'Log 10 A/A+ trades'],['BUILD THE RECEIPTS',Math.min(shots,10),10,'Upload 10 screenshots'],['WEEKLY DISCIPLINE',Math.min(weekPlan,5),5,'Follow plan on 5 trades this week']];
 const achievements=[['🏁','RUN STARTED',a.length>=1,'Log your first trade'],['📓','10 TRADES LOGGED',a.length>=10,'Build your first sample'],['🎯','PLAN LOCKED',plan>=10,'Follow plan on 10 trades'],['🏆','A+ EXECUTION',a.some(t=>t.grade==='A+'),'Log an A+ trade'],['👑','PERFECT EXECUTION',perfect>=1,'Plan + A/A+ + screenshot + notes'],['🔥','DISCIPLINE STREAK',st>=5,'5-day plan-followed streak'],['💯','100 TRADES',a.length>=100,'Log 100 trades'],['⚡','WIN STREAK',ws>=5,'Win 5 trades in a row']];
 let h='<section class="card rewardsHero rewardWide"><div class="title">🏦 CASA BANKO REWARDS</div><div class="rewardTop"><div><div class="label" style="margin-bottom:4px">BANKO BALANCE</div><div class="rewardBalance">'+balance.toLocaleString()+' BANKOS</div></div><div class="rewardLevel">'+li.name+'</div></div><div class="rewardTrack"><div class="rewardFill" style="width:'+li.pct+'%"></div></div><div class="hint">'+(li.i===li.levels.length-1?'MAX LEVEL REACHED':Math.max(0,li.next[1]-balance).toLocaleString()+' BANKOS TO '+li.next[0])+'</div><div class="rewardGrid"><div class="rewardBox"><div class="rewardK">💰 SYSTEM BANKOS</div><div class="rewardV">+'+bonus+'</div></div><div class="rewardBox"><div class="rewardK">🔥 DISCIPLINE STREAK</div><div class="rewardV">'+st+' DAYS</div></div><div class="rewardBox"><div class="rewardK">🏆 PERFECT TRADES</div><div class="rewardV">'+perfect+'</div></div><div class="rewardBox"><div class="rewardK">⚡ BEST WIN STREAK</div><div class="rewardV">'+ws+'</div></div></div></section>';
 h+='<section class="card rewardWide"><div class="title">🎯 MISSIONS</div><div class="hint">Complete disciplined trading actions to build your CASA BANKO run.</div>'+missions.map(m=>'<div class="missionBox"><div class="missionTop"><span>'+m[0]+'</span><span>'+m[1]+' / '+m[2]+'</span></div><div class="missionMeta">'+m[3]+'</div><div class="missionTrack"><div class="missionFill" style="width:'+Math.min(100,m[1]/m[2]*100)+'%"></div></div></div>').join('')+'</section>';
 h+='<section class="card rewardWide"><div class="title">🏆 ACHIEVEMENTS</div><div class="achievementGrid">'+achievements.map(x=>'<div class="achievement '+(x[2]?'unlocked':'locked')+'"><div class="achievementState">'+(x[2]?'UNLOCKED':'🔒')+'</div><div class="achievementIcon">'+x[0]+'</div><div class="achievementName">'+x[1]+'</div><div class="achievementMeta">'+x[3]+'</div></div>').join('')+'</div></section>';
 h+='<section class="card rewardWide"><div class="title">👑 LEVEL ROAD</div><div class="levelRoad">'+li.levels.map((x,i)=>'<div class="levelStep '+(i<li.i?'done':i===li.i?'current':'')+'"><div class="levelNum">LV '+(i+1)+'</div><div class="levelName">'+x[0]+'</div><div class="levelReq">'+x[1].toLocaleString()+' BANKOS '+(i<li.i?'✓':i===li.i?'•':'🔒')+'</div></div>').join('')+'</div></section>';
 if($('analyticsCharts'))$('analyticsCharts').innerHTML=h;
 }
 /* The old Analytics renderer is called by refreshAll(). Replace it at the source so it can never repaint the Rewards tab with old analytics content. */
 window.renderAnalytics=renderRewards;
 const oldOpen=window.openScreen;window.openScreen=function(name,remember=true){if(oldOpen)oldOpen(name,remember);if(name==='analytics')renderRewards()};
 document.addEventListener('DOMContentLoaded',()=>{let nav=document.querySelector('nav button[data-screen="analytics"]');if(nav)nav.innerHTML='🏆<br>REWARDS';let controls=document.querySelector('#analytics>.card');if(controls)controls.style.display='none';window.renderAnalytics=renderRewards;renderRewards();});
 window.renderRewards=renderRewards;
})();
