(()=>{
const KEY='casaBankoTrades';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const put=a=>{localStorage.setItem(KEY,JSON.stringify(a));window.dispatchEvent(new Event('storage'));if(typeof refreshAll==='function')refreshAll()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function isTL(t){const s=String(t?.source||'').toUpperCase(),id=String(t?.id||'');return s==='AUTO SYNC'||s.includes('TRADELOCKER')||id.startsWith('tl-')||t?.positionId!=null||t?.tradeLockerId!=null}
window.casaBankoEditSymbol=function(i){const a=get(),t=a[+i];if(!t)return;const current=t.symbolSource==='GENESIS'?(t.symbol||t.symbolName||''):(t.tempSymbol||t.symbol||t.symbolName||'');const v=prompt('Edit symbol name',current);if(v===null)return;const sym=v.trim().toUpperCase();if(!sym)return alert('Symbol name cannot be empty.');t.symbol=sym;t.symbolName=sym;t.tempSymbol=sym;t.symbolSource='MANUAL_TEMP';t.symbolVerified=false;put(a)};
function enhance(){const box=document.getElementById('manageTrades');if(!box)return;const rows=[...box.children];const trades=get();rows.forEach((row,pos)=>{if(row.querySelector('.cb-edit-symbol'))return;let idx=Number(row.dataset?.index);if(!Number.isInteger(idx)||!trades[idx]){const txt=row.textContent||'';idx=trades.findIndex((t,j)=>j>=pos&&((t.symbol&&txt.includes(t.symbol))||(t.symbolName&&txt.includes(t.symbolName))));if(idx<0)idx=pos<trades.length?pos:-1}if(idx<0||!trades[idx]||!isTL(trades[idx]))return;const b=document.createElement('button');b.type='button';b.className='cb-edit-symbol';b.textContent='EDIT SYMBOL';b.style.cssText='margin:6px 6px 0 0;padding:7px 10px;border:1px solid #9d7614;background:#17150f;color:#f1c84b;border-radius:7px;font-weight:700;cursor:pointer';b.onclick=e=>{e.stopPropagation();window.casaBankoEditSymbol(idx)};row.appendChild(b)})}
new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target?.id==='manageToggle')setTimeout(enhance,0)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();